#include <p18F14K50.inc>
	CONFIG CPUDIV = NOCLKDIV
	CONFIG USBDIV = OFF
	CONFIG FOSC   = IRC
	CONFIG PLLEN  = ON
	CONFIG FCMEN  = OFF
	CONFIG IESO   = OFF
	CONFIG PWRTEN = OFF
	CONFIG BOREN  = OFF
	CONFIG BORV   = 30
	CONFIG WDTEN  = OFF
	CONFIG WDTPS  = 32768
	CONFIG MCLRE  = OFF
	CONFIG HFOFST = OFF
	CONFIG STVREN = ON
	CONFIG LVP    = OFF
	CONFIG XINST  = OFF
	CONFIG BBSIZ  = OFF
	CONFIG CP0    = OFF
	CONFIG CP1    = OFF
	CONFIG CPB    = OFF
	CONFIG WRT0   = OFF
	CONFIG WRT1   = OFF
	CONFIG WRTB   = OFF
	CONFIG WRTC   = OFF
	CONFIG EBTR0  = OFF
	CONFIG EBTR1  = OFF
	CONFIG EBTRB  = OFF  
	
	org 0; start code at 0
	
Start:
	MOVLW 00h
	MOVWF TBLPTRU
	MOVLW 00h
	MOVWF TBLPTRH
	MOVLW 00h
	MOVWF TBLPTRL
	
	BSF	EECON1, EEPGD
	BCF EECON1, CFGS
	BSF EECON1, WREN
	BSF EECON1, FREE
	BSF EECON1, GIE
	
	MOVLW 55h
	MOVWF EECON2
	
	MOVLW 0AAh
	MOVWF EECON2
	BSF	EECON1, WR
	NOP
	NOP
	BSF INTCON, GIE
	END